# Book settings
# Learn more at https://jupyterbook.org/customize/config.html



title: Walmart Sales Forecasting
author: Aditya Joshi [www.adityajoshi.in]
logo: logo2.png
copyright: "2025"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache
  only_build_toc_files: true
  exclude_patterns:
    - 'main/forecasting.ipynb'
    - 'format_book.py'

# # Define the name of the latex output file for PDF builds
# latex:
#   latex_documents:
#     targetname: book.tex

# # Add a bibtex file so that we can create citations
# bibtex_bibfiles:
#   - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/joshiaditya0511/walmart-sales-forecasting  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: true
  home_page_in_navbar: false
  favicon: favicon.ico

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    html_css_files:
      - custom.css

    # mathjax_path: https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js
    # mathjax2_config: {
    #     'tex2jax': {
    #         'inlineMath': [['$', '$'], ['\\(', '\\)']],
    #         'processEscapes': True,
    #         'ignoreClass': 'document',
    #         'processClass': 'math|output_area',
    #     }
    # }
    # mathjax_options: {
    #     "async": "async",
    # }


